---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r Setup and data import}
require(MASS)
require(car)
require(RColorBrewer)
require(gplots)
setwd(getwd())
data <- read.csv('./stock data.csv')
Rise <- with(data, ifelse(End-Start < 0, 0, 1))
var.name <- colnames(data)
```

# EDA for the whole dataset

## Time-series plot

```{r Time course plot}
for(i in 3:24){
  plot(data[, 'Time0'], data[, i], type = 'l',
       main = var.name[i],
       xlab = 'Day from Feb 4, 2015',
       ylab = '')
}
```

```{r Data normalize}
z.tr <- function(x){ z <- (x-mean(x))/sd(x); z }
data.1 <- apply(data[, 3:24], 2, z.tr)
```

## Clustering

```{r Clustering}
dd <- dist(t(data.1))

cl.cp <- hclust(dd)
cl.av <- hclust(dd, method = 'average')
cl.d2 <- hclust(dd, method = 'ward.D2')

plot(cl.cp, hang = -1, xlab = '', ylab = 'Distance', main = 'Dendrogram (complete)')
rect.hclust(cl.cp, k = 4, border = 2:5)
plot(cl.av, hang = -1, xlab = '', ylab = 'Distance', main = 'Dendrogram (average)')
rect.hclust(cl.av, k = 4, border = 2:5)
plot(cl.d2, hang = -1, xlab = '', ylab = 'Distance', main = 'Dendrogram (ward.d2)')
rect.hclust(cl.d2, k = 4, border = 2:5)
```

## Principal component analysis

```{r PCA}
out.pca <- prcomp(data.1)
summary(out.pca)
# Plot the cumulative proportion of variance explained
plot(summary(out.pca)$importance[3, ], type = 'b',
     xlab = 'Principal Components',
     ylab = 'Cumulative Proportion')
abline(h = 0.9, col = 2)
# Call the coefficients of PC1-PC4
out.pca$rotation[, 1:4]
coul <- colorRampPalette(brewer.pal(9, 'RdBu'))(25)[25:1]
heatmap.2(as.matrix(out.pca$rotation[, 1:4]),
          Rowv = F, Colv = F,
          col = coul, dendrogram = 'none',
          density.info = 'none', trace = 'none',
          margins = c(5, 6))
# Combine PC1-4 with data.1 and Rise
data.2 <- as.data.frame(cbind(data.1, out.pca$x[, 1:4], Rise))
```

# Work on data with Rise

## Histograms comparing rise and fall

```{r Histograms}
rise.2 <- data.2[which(data.2$Rise == 1), ]
fall.2 <- data.2[which(data.2$Rise == 0), ]

# var.name <- colnames(rise.2)
# for (i in 1:26){
#   d.rise <- density(rise.2[, i])
#   d.fall <- density(fall.2[, i])
#   plot(d.rise, type = 'l', col = 2, main = var.name[i])
#   lines(d.fall, col = 3)
# }

par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(2, 4, 0, 0))
# PC1
d.rise <- density(rise.2[, 23])
d.fall <- density(fall.2[, 23])
plot(d.rise, type = 'l', col = 2, lwd = 2, main = '',
     xlim = c(-9, 9), xlab = '', ylim = c(0, 0.45),
     xaxt = 'n')
lines(d.fall, col = 3, lwd = 2, lty = 2)
axis(1, at = seq(-8, 8, 4), labels = NA)
text(-8, 0.42, 'PC1', font = 2, cex = 1.5)

# PC2
d.rise <- density(rise.2[, 24])
d.fall <- density(fall.2[, 24])
plot(d.rise, type = 'l', col = 2, lwd = 2, main = '',
     xlim = c(-9, 9), xlab = '', ylim = c(0, 0.45),
     xaxt = 'n', yaxt = 'n')
lines(d.fall, col = 3, lwd = 2, lty = 2)
axis(1, at = seq(-8, 8, 4), labels = NA)
axis(2, at = seq(0, 0.4, 0.1), labels = NA)
text(-8, 0.42, 'PC2', font = 2, cex = 1.5)

legend('topright', legend = c('Rise', 'Fall'),
       col = 2:3, lty = 1:2, lwd = 2, cex = 1.3, bty = 'n')

# PC3
d.rise <- density(rise.2[, 25])
d.fall <- density(fall.2[, 25])
plot(d.rise, type = 'l', col = 2, lwd = 2, main = '',
     xlim = c(-9, 9), xlab = '', ylim = c(0, 0.45),
     xaxt = 'n')
lines(d.fall, col = 3, lwd = 2, lty = 2)
axis(1, at = seq(-8, 8, 4))
text(-8, 0.42, 'PC3', font = 2, cex = 1.5)

# PC4
d.rise <- density(rise.2[, 26])
d.fall <- density(fall.2[, 26])
plot(d.rise, type = 'l', col = 2, lwd = 2, main = '',
     xlim = c(-9, 9), xlab = '', ylim = c(0, 0.45),
     xaxt = 'n', yaxt = 'n')
lines(d.fall, col = 3, lwd = 2, lty = 2)
axis(1, at = seq(-8, 8, 4))
axis(2, at = seq(0, 0.4, 0.1), labels = NA)
text(-8, 0.42, 'PC4', font = 2, cex = 1.5)

mtext('Estimated Density', 2, cex = 1.5, line = 2, outer = T)
```

## Scatter plots of PCs

```{r Scatter plot}
layout(mat = matrix(c(6, 0, 7, 4, 5, 0, 1, 2, 3), nc = 3, byrow = T))
par(mar = c(4, 4, 0.5, 0.5))
with(data.2, plot(PC1, PC2, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC1, PC3, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC1, PC4, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC2, PC3, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC2, PC4, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC3, PC4, col = 3-Rise, cex = 0.5, pch = 16))
with(data.2, plot(PC3, PC4, type = 'n', frame.plot = F, xaxt = 'n', yaxt = 'n',
     main = '', xlab = '', ylab = ''))
legend('topright', legend = c('Rise', 'Fall'), col = 2:3, pch = 16, cex = 2, bty = 'n')
```

## Logistic regression using PCs

```{r Logistic}
pc.name <- paste0('PC', 1:4)
index <- cbind(rep(0:1, each = 8),
               rep(rep(0:1, each = 4), times = 2),
               rep(rep(0:1, each = 2), times = 4),
               rep(0:1, times = 8))
index.1 <- index[-1, ]
aic <- c()
for (i in 1:nrow(index.1)){
  pc.name.1 <- pc.name[which(index.1[i, ] == 1)]
  data.k <- data.2[, c(pc.name.1, 'Rise')]
  out <- glm(Rise ~ ., data = data.k, family = 'binomial')
  aic[i] <- out$aic
  assign(paste0('model.', i), out)
}

out.stat <- as.data.frame(cbind(index.1, aic))
colnames(out.stat) <- c(pc.name, 'AIC')
out.stat[order(aic), ]
summary(model.15)
```

```{r Evaluation}
pred <- predict.glm(model.15, type = 'response')
cutoff <- seq(0, 1, 0.01)
sen <- spe <- acc <- c()
for (i in 1:length(cutoff)){
  pred.1 <- ifelse(pred < cutoff[i], 0, 1)
  pred.2 <- factor(pred.1, levels = c(0, 1))
  t.out <- table(Rise, pred.2)
  spe[i] <- t.out[1, 1]/rowSums(t.out)[1]
  sen[i] <- t.out[2, 2]/rowSums(t.out)[2]
  acc[i] <- (t.out[1, 1]+t.out[2, 2])/sum(t.out)
}
cutoff[which.max(acc)]
par(mfrow = c(1, 2), mar = c(4.5, 4.5, 4, 1))
plot(1-spe, sen, type = 's',
     xlab = '1-Specificity', ylab = 'Sensitivity', lwd = 2,
     xaxs = 'i', yaxs = 'i',
     main = 'ROC Curve', cex.axis = 1.2, cex.lab = 1.5, cex.main = 1.5)
abline(a = 0, b = 1, col = 8)
plot(cutoff, acc, type = 'l',
     xlab = 'Cutoff value', ylab = 'Accuracy', lwd = 2,
     cex.axis = 1.2, cex.lab = 1.5)
points(cutoff[which.max(acc)], acc[which.max(acc)],
       pch = 16, col = 2, cex = 1, lwd = 2)
```


# Work on data with Tomorrow-Rise

```{r Scatter Tomorrow}
data.3 <- cbind(data.2[-1021, ], Rise.lag1 = Rise[-1])
layout(mat = matrix(c(6, 0, 0, 4, 5, 0, 1, 2, 3), nc = 3, byrow = T))
par(mar = c(4, 4, 0.5, 0.5))
with(data.3, plot(PC1, PC2, col = 3-Rise.lag1, cex = 0.5, pch = 16))
with(data.3, plot(PC1, PC3, col = 3-Rise.lag1, cex = 0.5, pch = 16))
with(data.3, plot(PC1, PC4, col = 3-Rise.lag1, cex = 0.5, pch = 16))
with(data.3, plot(PC2, PC3, col = 3-Rise.lag1, cex = 0.5, pch = 16))
with(data.3, plot(PC2, PC4, col = 3-Rise.lag1, cex = 0.5, pch = 16))
with(data.3, plot(PC3, PC4, col = 3-Rise.lag1, cex = 0.5, pch = 16))
```

## Logistic regression on Tomorrow

```{r Logistic Tomorrow}
aic <- c()
for (i in 1:nrow(index.1)){
  pc.name.1 <- pc.name[which(index.1[i, ] == 1)]
  data.k <- data.3[, c(pc.name.1, 'Rise.lag1')]
  out <- glm(Rise.lag1 ~ ., data = data.k, family = 'binomial')
  aic[i] <- out$aic
  assign(paste0('model.', i), out)
}

out.stat <- as.data.frame(cbind(index.1, aic))
colnames(out.stat) <- c(pc.name, 'AIC')
out.stat[order(aic), ]
summary(model.8)
```

```{r Evaluation Tomorrow}
pred <- predict.glm(model.8, type = 'response')
cutoff <- seq(0, 1, 0.01)
sen <- spe <- acc <- c()
for (i in 1:length(cutoff)){
  pred.1 <- ifelse(pred < cutoff[i], 0, 1)
  pred.2 <- factor(pred.1, levels = c(0, 1))
  t.out <- table(data.3$Rise.lag1, pred.2)
  spe[i] <- t.out[1, 1]/rowSums(t.out)[1]
  sen[i] <- t.out[2, 2]/rowSums(t.out)[2]
  acc[i] <- (t.out[1, 1]+t.out[2, 2])/sum(t.out)
}
cutoff[which.max(acc)]
par(mfrow = c(1, 2), mar = c(4.5, 4.5, 4, 1))
plot(1-spe, sen, type = 's',
     xlab = '1-Specificity', ylab = 'Sensitivity', lwd = 2,
     xaxs = 'i', yaxs = 'i',
     main = 'ROC Curve', cex.axis = 1.2, cex.lab = 1.5, cex.main = 1.5)
abline(a = 0, b = 1, col = 8)
plot(cutoff, acc, type = 'l',
     xlab = 'Cutoff value', ylab = 'Accuracy', lwd = 2,
     cex.axis = 1.2, cex.lab = 1.5)
points(cutoff[which.max(acc)], acc[which.max(acc)],
       pch = 16, col = 2, cex = 1, lwd = 2)
```